### PR TITLE
Added a metric_base_path setting

### PR DESCRIPTION
**Pull request by standaloneSA**
I've taken on an environment that is, we shall say, "rich" with nooks and crannies where configs are stuffed, and inheritance is not used in any sane way. The end result is that I can't reasonably place a GRAPHITEPREFIX on every service, so I wanted a way to do it universally. Hence the metric_base_path config option that allows me to say "ALL METRICS SHALL BEGIN WITH THIS PATH". 

It should be good, but please test it and let me know what you think. 

Thanks! 

--Matt

### CODE REVIEW

**Comment by standaloneSA** [comment]
I'm going to hold off on this. It isn't working just yet. Sorry. I'll resubmit shortly.

**Comment by standaloneSA** [comment]
Fixed a bug where the setting wasn't actually taking effect. Created a small check to add the value to the metric object if the cfg['metric_base_path'] setting is defined, and leave it empty if not. This will allow people to upgrade without breaking their working configs, and add in the setting if they want.

**Comment by shawn-sterling** [comment]
Hey Matt, this looks great!

I will throw it on my test server for a day or two and if nothing explodes I'll merge it in.

I'm pumped you are using this in your new company. :)

Thanks for the patch!

Have a good weekend.

**Comment by standaloneSA** [comment]
You're very welcome. Thanks for writing awesome software that makes my job easier :-) I'll tell you about it in person! Are you going to be at LISA? I owe you a drink, plus I'll bring stickers for you :-)

**Comment by shawn-sterling** [comment]
I'm not going to lisa this year :( but I am going to re:invent next week! I wanna see what 18,000 attendees is like. I'm having trouble imagining it. heh.

**Comment by standaloneSA** [comment]
wow! It'll be a zoo! I went to VMworld once, and was blown away. It's like
a circus. Have a great time in Vegas! Let me know how it goes! :-D

On Sat, Sep 26, 2015 at 9:12 PM, Shawn Sterling <notifications@github.com>
wrote:

> I'm not going to lisa this year :( but I am going to re:invent next week!
> I wanna see what 18,000 attendees is like. I'm having trouble imagining it.
> heh.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/shawn-sterling/graphios/pull/87#issuecomment-143516439>
> .
>



-- 
LITTLE GIRL: But which cookie will you eat FIRST?
COOKIE MONSTER: Me think you have misconception of cookie-eating process.

**Comment by standaloneSA** [comment]
What's your mailing address, btw? I'll mail you some stickers :-)

--Matt


On Sat, Sep 26, 2015 at 9:29 PM, Matt Simmons <standalone.sysadmin@gmail.com
> wrote:

> wow! It'll be a zoo! I went to VMworld once, and was blown away. It's like
> a circus. Have a great time in Vegas! Let me know how it goes! :-D
>
> On Sat, Sep 26, 2015 at 9:12 PM, Shawn Sterling <notifications@github.com>
> wrote:
>
>> I'm not going to lisa this year :( but I am going to re:invent next week!
>> I wanna see what 18,000 attendees is like. I'm having trouble imagining it.
>> heh.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/shawn-sterling/graphios/pull/87#issuecomment-143516439>
>> .
>>
>
>
>
> --
> LITTLE GIRL: But which cookie will you eat FIRST?
> COOKIE MONSTER: Me think you have misconception of cookie-eating process.
>



-- 
LITTLE GIRL: But which cookie will you eat FIRST?
COOKIE MONSTER: Me think you have misconception of cookie-eating process.

**Comment by shawn-sterling** [comment]
Thanks Matt!

**Pull request merged**
